name: Metin2 Daily Event Reminder

on:
  schedule:
    - cron: '0 23,0 * * *'
  workflow_dispatch: # Allow manual trigger

permissions:
  contents: write
  pull-requests: write

jobs:
  send-reminders:
    runs-on: ubuntu-latest
    steps:
      - name: Check Lisbon time
        id: timecheck
        run: |
          HOUR=$(TZ="Europe/Lisbon" date +'%H')
          echo "It's $(TZ="Europe/Lisbon" date) in Lisbon."
          if [ "$HOUR" = "0" ]; then
            echo "run_job=true" >> $GITHUB_ENV
          else
            echo "run_job=false" >> $GITHUB_ENV
          fi

      - name: Checkout repository
        if: env.run_job == 'true'
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        if: env.run_job == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install pnpm
        if: env.run_job == 'true'
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Install dependencies
        if: env.run_job == 'true'
        run: pnpm install

      - name: Refresh cached data
        if: env.run_job == 'true'
        run: pnpm run refresh
        id: generate-data

      - name: Commit and push data files
        run: |
          git config --local user.email "igor.ruivo.97@gmail.com"
          git config --local user.name "Igor Ruivo"
          git add data/*.json || true

          # Check if there are staged changes
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            # Commit and push changes
            git commit -m "Refresh Tigerghost Metin2 Events - $(date)"
            git push
          fi

      - name: Send Discord notification on failure
        if: failure() && steps.generate-data.outcome == 'failure'
        run: |
          echo "Sending Discord notification for generate-data failure"

          # Create JSON payload for failure notification
          JSON_PAYLOAD="{\"content\":\"<@&1410116889740316684>\",\"embeds\":[{\"title\":\"❌ Erro ao Atualizar Eventos\",\"description\":\"Ocorreu um erro durante a atualização dos eventos do Metin2 Tigerghost. Os eventos poderão estar desatualizados.\",\"color\":16711680,\"timestamp\":\"$(date -u +%Y-%m-%dT%H:%M:%S.000Z)\"}]}"

          curl -X POST "$DISCORD_WEBHOOK_URL" \
            -H "Content-Type: application/json" \
            -d "$JSON_PAYLOAD"
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Run reminder script
        if: env.run_job == 'true'
        run: pnpm run daily
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}