name: Metin2 Daily Event Reminder

on:
  schedule:
    - cron: '0 23,0 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  send-reminders:
    runs-on: ubuntu-latest
    steps:
      - name: Check Lisbon time
        id: timecheck
        run: |
          HOUR=$(TZ="Europe/Lisbon" date +'%H')
          echo "It's $(TZ="Europe/Lisbon" date) in Lisbon."
          if [ "$HOUR" = "0" ]; then
            echo "run_job=true" >> $GITHUB_ENV
          else
            echo "run_job=false" >> $GITHUB_ENV
          fi

      - name: Checkout repository
        if: env.run_job == 'true'
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        if: env.run_job == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install pnpm
        if: env.run_job == 'true'
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Install dependencies
        if: env.run_job == 'true'
        run: pnpm install

      - name: Refresh cached data
        if: env.run_job == 'true'
        run: pnpm run refresh

      - name: Run reminder script
        if: env.run_job == 'true'
        run: pnpm run daily
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}